# Generated by Django 4.2.7 on 2023-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestate",
            name="exclusive_area",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="realestate",
            name="floor",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="realestate",
            name="year_of_construction",
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="realestatetrade",
            name="trade_day",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="realestatetrade",
            name="trade_month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="realestatetrade",
            name="trade_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="realestatetrade",
            name="trade_year",
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="region",
            name="dong_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="region",
            name="gu_gun_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="region",
            name="region_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="region",
            name="si_do_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
