# Generated by Django 4.2.7 on 2023-11-08 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0002_realestate_exclusive_area_realestate_floor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="exclusive_area",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="floor",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="year_of_construction",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="realestatetrade",
            name="trade_day",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="realestatetrade",
            name="trade_month",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="realestatetrade",
            name="trade_year",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_code",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
