# Generated by Django 4.2.7 on 2023-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_realestate_exclusive_area_realestate_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="gu_gun_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="region",
            name="si_do_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
