# Generated by Django 4.2.7 on 2023-11-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_realestate_exclusive_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='gu_gun_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='si_do_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='exclusive_area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestates', to='trades.region'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='year_of_construction',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='realestatetrade',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestatetrades', to='trades.realestate'),
        ),
        migrations.AlterField(
            model_name='realestatetrade',
            name='trade_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='realestatetrade',
            name='trade_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='realestatetrade',
            name='trade_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.IntegerField(default=0),
        ),
    ]
